title: Exploit Notes
description: Sticky notes for pentesting. Search hacking techniques and tools for penetration testings, bug bounty, CTF. 
author: hdks
github:
  name: GitHub
  url: https://github.com/hideckies/exploit-notes
  icon: /assets/github.png
twitter:
  name: Twitter
  url: https://twitter.com/hideckies
  icon: /assets/twitter.png
tags:
  - Active Directory
  - Cloud
  - Container
  - Content Discovery
  - Cryptography
  - DNS
  - Email
  - Malware
  - Privilege Escalation
  - Reconnaissance
  - Reverse Engineering
  - Reverse Shell
  - SSRF
  - Steganography
  - XSS
  - Web
  - Windows