title: Exploit Notes
description: Sticky notes for pentesting.
me:
  nickname: hx15h1gur0
  name: H1d3k1
  fullname: H1d3k1 15h1gur0
socials:
  - name: Twitter
    url: https://twitter.com/hideckies
    icon: /assets/twitter.png
  - name: Mastodon
    url: https://infosec.exchange/@hx15h1gur0
    icon:
  - name: GitHub
    url: https://github.com/hideckies/exploitnotes
    icon: /assets/github.png
tags:
  - Active Directory
  - Cloud
  - Cryptography
  - DNS
  - Malware
  - Privilege Escalation
  - Reverse Engineering
  - Reverse Shell
  - SSRF
  - Steganography
  - XSS
  - Web
  - Windows