title: Exploit Notes
description: Sticky notes for pentesting.
me:
  nickname: hx15h1gur0
  name: H1d3k1
  fullname: H1d3k1 15h1gur0
github:
  name: GitHub
  url: https://github.com/hideckies/exploit-notes
  icon: /assets/github.png
twitter:
  name: Twitter
  url: https://twitter.com/hideckies
  icon: /assets/twitter.png
mastodon:
  name: Mastodon
  url: https://infosec.exchange/@hx15h1gur0
  icon:
tags:
  - Active Directory
  - Cloud
  - Content Discovery
  - Cryptography
  - DNS
  - Malware
  - Privilege Escalation
  - Reconnaissance
  - Reverse Engineering
  - Reverse Shell
  - SSRF
  - Steganography
  - XSS
  - Web
  - Windows